apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prostackhub-gitops-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MuhammadIslahUddin/Prostackhub_Task-5_GitOps-Pipeline.git
    targetRevision: main
    path: helm/gitops-app

  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
