replicaCount: 2

image:
  repository: ghcr.io/muhammadislahuddin/prostackhub-task-5-gitops-pipeline
  tag: "6e7cef438b11b0a3eeec54a8bf8f6bfca1eb05ef"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  targetPort: 5000

resources: {}
