name: CI/CD - GitOps Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest -v

  build-and-push:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/muhammadislahuddin/prostackhub-task-5-gitops-pipeline:${{ github.sha }}
            ghcr.io/muhammadislahuddin/prostackhub-task-5-gitops-pipeline:latest

      - name: Update Helm image tag
        run: |
          sed -i "s/^  tag: .*/  tag: \"${GITHUB_SHA}\"/" helm/gitops-app/values.yaml

          echo "Updated Helm values:"
          grep "tag:" helm/gitops-app/values.yaml

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add helm/gitops-app/values.yaml

          git commit -m "Update image tag to ${GITHUB_SHA} [skip ci]"

          git push
